### PR TITLE
Small improvements I will need for Artemis

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by tabish121** [comment]
There seems to be changes in the MessageImpl that don't have anything to do with the issue at hand and probably would deserve their own JIRA.

**Comment by clebertsuconic** [comment]
@tabish121 actually this is about moving the TLS logic from MessageIMpl to its own class. I only added an @Override into toString being non related to this.. I will remove that to avoid any confusion

**Comment by tabish121** [comment]
So you've created two JIRAs but only created one pull request on not reference either JIRA in it?

**Comment by clebertsuconic** [comment]
@tabish121 There are two commits on this PR, one for each JIRA.

Each commit is referring the JIRA on it, which is what we need as a link. The PR is just a tool to contribute changes, but if it is required a PR per JIRA I can make the change.

**Comment by tabish121** [comment]
Please follow the same recommendations that you'd make for someone submitting a PR to Artemis.  If you raise the PR with the JIRA key in the title, a bot will raise a note against the JIRA for open/close and also relay future comments to the JIRA.  Also, having one PR per issue will allow separate comments on the merits of each with less confusion

**Comment by clebertsuconic** [comment]
We actually send / accept PRs for multiple issues on Artemis all the time... but I will separate them.

**Comment by clebertsuconic** [comment]
@tabish121 you could also refer the comments by clicking on the commit. github will offer a global view, or per commit. It's about the interface.. 

anyway this is now superseded by #6 and #7

**Comment by tabish121** [comment]
@clebertsuconic  while that may be true, since your initial PR didn't reference either issue, none of that discussion gets logged into the JIRA which is the bit you seem to be missing

**Pull request closed without merging**
